## Popularity Based Reccomensation System

In [ ]:
import pandas as pd
import numpy as np

In [2]:
movie_names = pd.read_csv("movies.csv")
movie_names.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [10]:
movie_names.shape

(9125, 3)

In [9]:
movie_ratings = pd.read_csv("ratings.csv")
movie_ratings.head()
movie_ratings.shape

(100004, 4)

In [5]:
movie_data = pd.merge(movie_ratings, movie_names, on='movieId')
movie_data.head()

   userId  movieId  rating   timestamp                   title genres
0       1       31     2.5  1260759144  Dangerous Minds (1995)  Drama
1       7       31     3.0   851868750  Dangerous Minds (1995)  Drama
2      31       31     4.0  1273541953  Dangerous Minds (1995)  Drama
3      32       31     4.0   834828440  Dangerous Minds (1995)  Drama
4      36       31     3.0   847057202  Dangerous Minds (1995)  Drama

In [7]:
movie_data.shape

(100004, 6)

## Criteria for Popularity Based Reccommendation Systems
1. Movies with the highest rating
2. Number of Views

### Average ratings of movies

In [11]:
movie_data.groupby('title')['rating'].mean().head()

title
"Great Performances" Cats (1998)           1.750000
$9.99 (2008)                               3.833333
'Hellboy': The Seeds of Creation (2004)    2.000000
'Neath the Arizona Skies (1934)            0.500000
'Round Midnight (1986)                     2.250000
Name: rating, dtype: float64

In [13]:
# sorting them with movies wwith highest ratings
movie_data.groupby('title')['rating'].mean().sort_values(ascending=False).head(30)

title
Ivan Vasilievich: Back to the Future (Ivan Vasilievich menyaet professiyu) (1973)    5.0
Alien Escape (1995)                                                                  5.0
Boiling Point (1993)                                                                 5.0
Bone Tomahawk (2015)                                                                 5.0
Borgman (2013)                                                                       5.0
Survive and Advance (2013)                                                           5.0
Supercop 2 (Project S) (Chao ji ji hua) (1993)                                       5.0
Last Dragon, The (1985)                                                              5.0
Boy Crazy (2009)                                                                     5.0
Brandon Teena Story, The (1998)                                                      5.0
Straight-Jacket (2004)                                                               5.0
Storefront Hitchcock (1997)                                                          5.0
Latter Days (2003)                                                                   5.0
Howl (2010)                                                                          5.0
Step Into Liquid (2002)                                                              5.0
Brooklyn (2015)                                                                      5.0
Brother, Can You Spare a Dime? (1975)                                                5.0
Bobby (2006)                                                                         5.0
Sympathy for Mr. Vengeance (Boksuneun naui geot) (2002)                              5.0
Land of Silence and Darkness (Land des Schweigens und der Dunkelheit) (1971)         5.0
The Beatles: Eight Days a Week - The Touring Years (2016)                            5.0
The Car (1977)                                                                       5.0
Bill Hicks: Relentless (1992)                                                        5.0
Bill Hicks: Revelations (1993)                                                       5.0
The Brave Little Toaster Goes to Mars (1998)                                         5.0
The Biggest Fan (2002)                                                               5.0
The Big Gay Musical (2009)                                                           5.0
Bite the Bullet (1975)                                                               5.0
Lamerica (1994)                                                                      5.0
I Think I Do (1997)                                                                  5.0
Name: rating, dtype: float64

### Rating Count

In [15]:
movie_data.groupby('title')['rating'].count().sort_values(ascending=False).head()

title
Forrest Gump (1994)                          341
Pulp Fiction (1994)                          324
Shawshank Redemption, The (1994)             311
Silence of the Lambs, The (1991)             304
Star Wars: Episode IV - A New Hope (1977)    291
Name: rating, dtype: int64

In [16]:
movie_data[['title', 'rating']]

                                       title  rating
0                     Dangerous Minds (1995)     2.5
1                     Dangerous Minds (1995)     3.0
2                     Dangerous Minds (1995)     4.0
3                     Dangerous Minds (1995)     4.0
4                     Dangerous Minds (1995)     3.0
...                                      ...     ...
99999               War of the Worlds (2005)     2.5
100000                       Box, The (2009)     3.5
100001                 Pie in the Sky (1996)     3.0
100002                   Summer Catch (2001)     1.0
100003  6th Man, The (Sixth Man, The) (1997)     1.0

[100004 rows x 2 columns]

In [18]:
# calculate the average ratings
ratings_mean_count = pd.DataFrame(movie_data.groupby('title')['rating'].mean())

In [19]:
ratings_mean_count

                                             rating
title
"Great Performances" Cats (1998)           1.750000
$9.99 (2008)                               3.833333
'Hellboy': The Seeds of Creation (2004)    2.000000
'Neath the Arizona Skies (1934)            0.500000
'Round Midnight (1986)                     2.250000
...                                             ...
xXx (2002)                                 2.478261
xXx: State of the Union (2005)             1.000000
¡Three Amigos! (1986)                      3.258065
À nous la liberté (Freedom for Us) (1931)  4.500000
İtirazım Var (2014)                        3.500000

[9064 rows x 1 columns]

### calculate the count of the rating and add to the average ratings above

In [22]:
ratings_mean_count['rating_count'] = movie_data.groupby('title')['rating'].count()

In [23]:
ratings_mean_count

                                             rating  rating_count
title
"Great Performances" Cats (1998)           1.750000             2
$9.99 (2008)                               3.833333             3
'Hellboy': The Seeds of Creation (2004)    2.000000             1
'Neath the Arizona Skies (1934)            0.500000             1
'Round Midnight (1986)                     2.250000             2
...                                             ...           ...
xXx (2002)                                 2.478261            23
xXx: State of the Union (2005)             1.000000             1
¡Three Amigos! (1986)                      3.258065            31
À nous la liberté (Freedom for Us) (1931)  4.500000             1
İtirazım Var (2014)                        3.500000             1

[9064 rows x 2 columns]

In [24]:
ratings_mean_count['rating'] = round(ratings_mean_count['rating'],1)

In [26]:
ratings_mean_count.tail()

                                           rating  rating_count
title
xXx (2002)                                    2.5            23
xXx: State of the Union (2005)                1.0             1
¡Three Amigos! (1986)                         3.3            31
À nous la liberté (Freedom for Us) (1931)     4.5             1
İtirazım Var (2014)                           3.5             1

In [28]:
ratings_mean_count = ratings_mean_count[(ratings_mean_count['rating'] > 3) & (ratings_mean_count['rating_count'] > 100) ]

In [30]:
ratings_mean_count.head()

                              rating  rating_count
title
2001: A Space Odyssey (1968)     3.9           123
Airplane! (1980)                 3.8           106
Aladdin (1992)                   3.7           215
Alien (1979)                     4.0           127
Aliens (1986)                    3.9           125

In [31]:
ratings_mean_count = ratings_mean_count.sort_values(by = 'rating', ascending=False)

In [32]:
ratings_mean_count.head(10)

                                                    rating  rating_count
title
Godfather, The (1972)                                  4.5           200
Shawshank Redemption, The (1994)                       4.5           311
Usual Suspects, The (1995)                             4.4           201
Godfather: Part II, The (1974)                         4.4           135
Pulp Fiction (1994)                                    4.3           324
Fargo (1996)                                           4.3           224
One Flew Over the Cuckoo's Nest (1975)                 4.3           144
Schindler's List (1993)                                4.3           244
Taxi Driver (1976)                                     4.2           118
Lord of the Rings: The Fellowship of the Ring, ...     4.2           200